export interface SuburbData {
  name: string;
  slug: string;
  median2br: number;
  p10: number;
  p90: number;
  n: number;
  negoPercent: number;
  negoAmtPw: number;
  pressureLevel: "Low" | "Medium" | "High" | "Very High";
  pressureDots: number; // 1-5
  qoqTrend: number; // percent
  trendDir: "up" | "flat" | "down";
}

export const SUBURBS: SuburbData[] = [
  {
    name: "Brunswick",
    slug: "brunswick",
    median2br: 520,
    p10: 430,
    p90: 640,
    n: 847,
    negoPercent: 58,
    negoAmtPw: 27,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 3.2,
    trendDir: "up",
  },
  {
    name: "Fitzroy",
    slug: "fitzroy",
    median2br: 570,
    p10: 480,
    p90: 720,
    n: 612,
    negoPercent: 44,
    negoAmtPw: 19,
    pressureLevel: "Very High",
    pressureDots: 5,
    qoqTrend: 4.8,
    trendDir: "up",
  },
  {
    name: "Northcote",
    slug: "northcote",
    median2br: 490,
    p10: 400,
    p90: 600,
    n: 534,
    negoPercent: 62,
    negoAmtPw: 31,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: 1.9,
    trendDir: "up",
  },
  {
    name: "Richmond",
    slug: "richmond",
    median2br: 550,
    p10: 460,
    p90: 680,
    n: 489,
    negoPercent: 51,
    negoAmtPw: 24,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 0.4,
    trendDir: "flat",
  },
  {
    name: "St Kilda",
    slug: "st-kilda",
    median2br: 530,
    p10: 440,
    p90: 660,
    n: 421,
    negoPercent: 55,
    negoAmtPw: 22,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: -0.8,
    trendDir: "flat",
  },
  {
    name: "Coburg",
    slug: "coburg",
    median2br: 440,
    p10: 360,
    p90: 550,
    n: 312,
    negoPercent: 67,
    negoAmtPw: 34,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: -1.2,
    trendDir: "down",
  },
  {
    name: "Prahran",
    slug: "prahran",
    median2br: 600,
    p10: 500,
    p90: 750,
    n: 287,
    negoPercent: 39,
    negoAmtPw: 16,
    pressureLevel: "Very High",
    pressureDots: 5,
    qoqTrend: 5.1,
    trendDir: "up",
  },
  {
    name: "Collingwood",
    slug: "collingwood",
    median2br: 560,
    p10: 470,
    p90: 700,
    n: 398,
    negoPercent: 47,
    negoAmtPw: 21,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 2.6,
    trendDir: "up",
  },
  {
    name: "Carlton",
    slug: "carlton",
    median2br: 540,
    p10: 450,
    p90: 670,
    n: 356,
    negoPercent: 49,
    negoAmtPw: 20,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 1.4,
    trendDir: "up",
  },
  {
    name: "South Yarra",
    slug: "south-yarra",
    median2br: 610,
    p10: 510,
    p90: 760,
    n: 445,
    negoPercent: 38,
    negoAmtPw: 15,
    pressureLevel: "Very High",
    pressureDots: 5,
    qoqTrend: 4.2,
    trendDir: "up",
  },
  {
    name: "Footscray",
    slug: "footscray",
    median2br: 420,
    p10: 340,
    p90: 520,
    n: 278,
    negoPercent: 65,
    negoAmtPw: 30,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: 0.8,
    trendDir: "flat",
  },
  {
    name: "Preston",
    slug: "preston",
    median2br: 430,
    p10: 350,
    p90: 530,
    n: 241,
    negoPercent: 64,
    negoAmtPw: 29,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: 1.1,
    trendDir: "up",
  },
  {
    name: "Docklands",
    slug: "docklands",
    median2br: 650,
    p10: 550,
    p90: 820,
    n: 312,
    negoPercent: 42,
    negoAmtPw: 18,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: -2.1,
    trendDir: "down",
  },
  {
    name: "South Melbourne",
    slug: "south-melbourne",
    median2br: 590,
    p10: 490,
    p90: 730,
    n: 267,
    negoPercent: 45,
    negoAmtPw: 20,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 2.3,
    trendDir: "up",
  },
  {
    name: "Port Melbourne",
    slug: "port-melbourne",
    median2br: 570,
    p10: 470,
    p90: 710,
    n: 198,
    negoPercent: 50,
    negoAmtPw: 22,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 1.7,
    trendDir: "up",
  },
  {
    name: "Brunswick East",
    slug: "brunswick-east",
    median2br: 500,
    p10: 415,
    p90: 620,
    n: 189,
    negoPercent: 60,
    negoAmtPw: 26,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: 2.8,
    trendDir: "up",
  },
  {
    name: "Thornbury",
    slug: "thornbury",
    median2br: 460,
    p10: 380,
    p90: 570,
    n: 211,
    negoPercent: 61,
    negoAmtPw: 28,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: 1.5,
    trendDir: "up",
  },
  {
    name: "Moonee Ponds",
    slug: "moonee-ponds",
    median2br: 450,
    p10: 370,
    p90: 560,
    n: 167,
    negoPercent: 63,
    negoAmtPw: 30,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: 0.6,
    trendDir: "flat",
  },
  {
    name: "Camberwell",
    slug: "camberwell",
    median2br: 540,
    p10: 450,
    p90: 670,
    n: 223,
    negoPercent: 52,
    negoAmtPw: 23,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 1.9,
    trendDir: "up",
  },
  {
    name: "Hawthorn",
    slug: "hawthorn",
    median2br: 560,
    p10: 460,
    p90: 690,
    n: 256,
    negoPercent: 48,
    negoAmtPw: 21,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 2.0,
    trendDir: "up",
  },
  {
    name: "Abbotsford",
    slug: "abbotsford",
    median2br: 545,
    p10: 455,
    p90: 675,
    n: 201,
    negoPercent: 49,
    negoAmtPw: 22,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 3.1,
    trendDir: "up",
  },
  {
    name: "Windsor",
    slug: "windsor",
    median2br: 520,
    p10: 435,
    p90: 645,
    n: 178,
    negoPercent: 54,
    negoAmtPw: 23,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 1.8,
    trendDir: "up",
  },
  {
    name: "Elsternwick",
    slug: "elsternwick",
    median2br: 530,
    p10: 440,
    p90: 660,
    n: 156,
    negoPercent: 53,
    negoAmtPw: 23,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 1.3,
    trendDir: "up",
  },
  {
    name: "Kensington",
    slug: "kensington",
    median2br: 480,
    p10: 395,
    p90: 595,
    n: 134,
    negoPercent: 59,
    negoAmtPw: 26,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: 2.4,
    trendDir: "up",
  },
];

export const SUBURB_NAMES = SUBURBS.map((s) => s.name);

export function getSuburbBySlug(slug: string): SuburbData | undefined {
  return SUBURBS.find((s) => s.slug === slug);
}

export function getSuburbByName(name: string): SuburbData {
  return SUBURBS.find(
    (s) => s.name.toLowerCase() === name.toLowerCase()
  ) ?? SUBURBS[0];
}
