export interface SuburbData {
  name: string;
  slug: string;
  median2br: number;
  p10: number;
  p90: number;
  n: number;
  negoPercent: number;
  negoAmtPw: number;
  pressureLevel: "Low" | "Medium" | "High" | "Very High";
  pressureDots: number; // 1-5
  qoqTrend: number; // percent
  trendDir: "up" | "flat" | "down";
}

// Suburb baseline data — real Domain.com.au asking prices, April 2026, n=486 listings
export const SUBURBS: SuburbData[] = [
  {
    name: "Brunswick",
    slug: "brunswick",
    median2br: 675,
    p10: 570,
    p90: 795,
    n: 29,
    negoPercent: 58,
    negoAmtPw: 27,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 3.2,
    trendDir: "up",
  },
  {
    name: "Fitzroy",
    slug: "fitzroy",
    median2br: 750,
    p10: 650,
    p90: 1050,
    n: 40,
    negoPercent: 44,
    negoAmtPw: 19,
    pressureLevel: "Very High",
    pressureDots: 5,
    qoqTrend: 4.8,
    trendDir: "up",
  },
  {
    name: "Northcote",
    slug: "northcote",
    median2br: 670,
    p10: 590,
    p90: 800,
    n: 18,
    negoPercent: 62,
    negoAmtPw: 31,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: 1.9,
    trendDir: "up",
  },
  {
    name: "Richmond",
    slug: "richmond",
    median2br: 712,
    p10: 650,
    p90: 880,
    n: 6,
    negoPercent: 51,
    negoAmtPw: 24,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 0.4,
    trendDir: "flat",
  },
  {
    name: "St Kilda",
    slug: "st-kilda",
    median2br: 720,
    p10: 560,
    p90: 895,
    n: 23,
    negoPercent: 55,
    negoAmtPw: 22,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: -0.8,
    trendDir: "flat",
  },
  {
    name: "Coburg",
    slug: "coburg",
    median2br: 570,
    p10: 500,
    p90: 650,
    n: 13,
    negoPercent: 67,
    negoAmtPw: 34,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: -1.2,
    trendDir: "down",
  },
  {
    name: "Prahran",
    slug: "prahran",
    median2br: 750,
    p10: 560,
    p90: 975,
    n: 41,
    negoPercent: 39,
    negoAmtPw: 16,
    pressureLevel: "Very High",
    pressureDots: 5,
    qoqTrend: 5.1,
    trendDir: "up",
  },
  {
    name: "Collingwood",
    slug: "collingwood",
    median2br: 750,
    p10: 600,
    p90: 980,
    n: 25,
    negoPercent: 47,
    negoAmtPw: 21,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 2.6,
    trendDir: "up",
  },
  {
    name: "Carlton",
    slug: "carlton",
    median2br: 750,
    p10: 650,
    p90: 975,
    n: 26,
    negoPercent: 49,
    negoAmtPw: 20,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 1.4,
    trendDir: "up",
  },
  {
    name: "South Yarra",
    slug: "south-yarra",
    median2br: 675,
    p10: 520,
    p90: 880,
    n: 11,
    negoPercent: 38,
    negoAmtPw: 15,
    pressureLevel: "Very High",
    pressureDots: 5,
    qoqTrend: 4.2,
    trendDir: "up",
  },
  {
    name: "Footscray",
    slug: "footscray",
    median2br: 420,
    p10: 340,
    p90: 520,
    n: 278,
    negoPercent: 65,
    negoAmtPw: 30,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: 0.8,
    trendDir: "flat",
  },
  {
    name: "Preston",
    slug: "preston",
    median2br: 550,
    p10: 520,
    p90: 620,
    n: 15,
    negoPercent: 64,
    negoAmtPw: 29,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: 1.1,
    trendDir: "up",
  },
  {
    name: "Docklands",
    slug: "docklands",
    median2br: 920,
    p10: 720,
    p90: 965,
    n: 3,
    negoPercent: 42,
    negoAmtPw: 18,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: -2.1,
    trendDir: "down",
  },
  {
    name: "South Melbourne",
    slug: "south-melbourne",
    median2br: 780,
    p10: 650,
    p90: 920,
    n: 39,
    negoPercent: 45,
    negoAmtPw: 20,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 2.3,
    trendDir: "up",
  },
  {
    name: "Port Melbourne",
    slug: "port-melbourne",
    median2br: 908,
    p10: 650,
    p90: 1100,
    n: 28,
    negoPercent: 50,
    negoAmtPw: 22,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 1.7,
    trendDir: "up",
  },
  {
    name: "Brunswick East",
    slug: "brunswick-east",
    median2br: 630,
    p10: 600,
    p90: 650,
    n: 3,
    negoPercent: 60,
    negoAmtPw: 26,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: 2.8,
    trendDir: "up",
  },
  {
    name: "Thornbury",
    slug: "thornbury",
    median2br: 630,
    p10: 550,
    p90: 720,
    n: 9,
    negoPercent: 61,
    negoAmtPw: 28,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: 1.5,
    trendDir: "up",
  },
  {
    name: "Moonee Ponds",
    slug: "moonee-ponds",
    median2br: 537,
    p10: 460,
    p90: 725,
    n: 16,
    negoPercent: 63,
    negoAmtPw: 30,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: 0.6,
    trendDir: "flat",
  },
  {
    name: "Camberwell",
    slug: "camberwell",
    median2br: 640,
    p10: 525,
    p90: 850,
    n: 26,
    negoPercent: 52,
    negoAmtPw: 23,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 1.9,
    trendDir: "up",
  },
  {
    name: "Hawthorn",
    slug: "hawthorn",
    median2br: 687,
    p10: 600,
    p90: 875,
    n: 22,
    negoPercent: 48,
    negoAmtPw: 21,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 2.0,
    trendDir: "up",
  },
  {
    name: "Abbotsford",
    slug: "abbotsford",
    median2br: 672,
    p10: 550,
    p90: 880,
    n: 20,
    negoPercent: 49,
    negoAmtPw: 22,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 3.1,
    trendDir: "up",
  },
  {
    name: "Windsor",
    slug: "windsor",
    median2br: 687,
    p10: 600,
    p90: 895,
    n: 10,
    negoPercent: 54,
    negoAmtPw: 23,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 1.8,
    trendDir: "up",
  },
  {
    name: "Elsternwick",
    slug: "elsternwick",
    median2br: 670,
    p10: 520,
    p90: 890,
    n: 43,
    negoPercent: 53,
    negoAmtPw: 23,
    pressureLevel: "High",
    pressureDots: 4,
    qoqTrend: 1.3,
    trendDir: "up",
  },
  {
    name: "Kensington",
    slug: "kensington",
    median2br: 675,
    p10: 595,
    p90: 825,
    n: 17,
    negoPercent: 59,
    negoAmtPw: 26,
    pressureLevel: "Medium",
    pressureDots: 3,
    qoqTrend: 2.4,
    trendDir: "up",
  },
];

export const SUBURB_NAMES = SUBURBS.map((s) => s.name);

export function getSuburbBySlug(slug: string): SuburbData | undefined {
  return SUBURBS.find((s) => s.slug === slug);
}

export function getSuburbByName(name: string): SuburbData {
  return SUBURBS.find(
    (s) => s.name.toLowerCase() === name.toLowerCase()
  ) ?? SUBURBS[0];
}
