"""
update_app_data.py
==================
Generates updated TypeScript files for lib/suburbs.ts and lib/model.ts
from the derived baselines and attribute weights.

Input:  data/suburb_baselines.json
        data/attribute_weights.json
Output: data/updated_suburbs.ts   (review before applying)
        data/updated_model.ts     (review before applying)

Usage:
    python scripts/update_app_data.py

To apply:
    cp data/updated_suburbs.ts lib/suburbs.ts
    cp data/updated_model.ts lib/model.ts
"""

import json
import sys
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"
LIB_DIR = Path(__file__).parent.parent / "lib"

BASELINES_FILE = DATA_DIR / "suburb_baselines.json"
WEIGHTS_FILE = DATA_DIR / "attribute_weights.json"
OUT_SUBURBS = DATA_DIR / "updated_suburbs.ts"
OUT_MODEL = DATA_DIR / "updated_model.ts"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_json(path: Path) -> dict | list:
    if not path.exists():
        print(f"File not found: {path}")
        sys.exit(1)
    return json.loads(path.read_text())


def determine_pressure(median: int, p10: int, p90: int, count: int) -> tuple[str, int]:
    """
    Estimate market pressure from spread and price level.
    Higher median + tighter spread = more pressure.
    """
    spread = p90 - p10
    spread_ratio = spread / median if median else 1

    if median >= 600 and spread_ratio < 0.45:
        return "Very High", 5
    if median >= 540 or spread_ratio < 0.35:
        return "High", 4
    if median >= 470:
        return "Medium", 3
    return "Low", 2


def suburb_slug(name: str) -> str:
    return name.lower().replace(" ", "-")


# ---------------------------------------------------------------------------
# Build suburb data
# ---------------------------------------------------------------------------

def build_suburb_entries(baselines: list[dict]) -> list[dict]:
    """
    Collapse suburb baselines into the SuburbData schema used by lib/suburbs.ts.
    Uses 2BR apartment as the reference point (matching the existing model).
    Falls back to overall 2BR median if no apartment data exists.
    """
    # Group by suburb
    by_suburb: dict[str, dict] = {}

    for b in baselines:
        suburb = b["suburb"]
        if suburb not in by_suburb:
            by_suburb[suburb] = {"all": [], "apt_2br": None}

        if b["property_type"] == "apartment" and b["bedrooms"] == 2:
            by_suburb[suburb]["apt_2br"] = b
        by_suburb[suburb]["all"].append(b)

    entries = []
    for suburb, data in sorted(by_suburb.items()):
        ref = data["apt_2br"]

        if ref is None:
            # Fall back to 2BR of any type
            two_brs = [b for b in data["all"] if b["bedrooms"] == 2]
            if not two_brs:
                continue
            # Use highest-count group
            ref = max(two_brs, key=lambda x: x["count"])

        if ref["count"] < 5:
            print(f"  [WARN] {suburb}: only {ref['count']} 2BR apartment listings — "
                  "consider collecting more data before applying")

        pressure_level, pressure_dots = determine_pressure(
            ref["median_rent"], ref["p10"], ref["p90"], ref["count"]
        )

        entries.append(
            {
                "name": suburb,
                "slug": suburb_slug(suburb),
                "median2br": ref["median_rent"],
                "p10": ref["p10"],
                "p90": ref["p90"],
                "n": ref["count"],
                # negoPercent / negoAmtPw / qoqTrend cannot be derived from
                # a static snapshot — keep placeholder values for now
                "negoPercent": 50,
                "negoAmtPw": round(ref["median_rent"] * 0.04),
                "pressureLevel": pressure_level,
                "pressureDots": pressure_dots,
                "qoqTrend": 0.0,
                "trendDir": "flat",
            }
        )

    return entries


# ---------------------------------------------------------------------------
# TypeScript code generation
# ---------------------------------------------------------------------------

SUBURBS_HEADER = """\
// AUTO-GENERATED by scripts/update_app_data.py
// Source: data/suburb_baselines.json (derived from Domain.com.au listings)
// Review carefully before committing — negoPercent, negoAmtPw, and qoqTrend
// are still placeholder values; only the rent figures are data-derived.

export interface SuburbData {
  name: string;
  slug: string;
  median2br: number;
  p10: number;
  p90: number;
  n: number;
  negoPercent: number;
  negoAmtPw: number;
  pressureLevel: "Low" | "Medium" | "High" | "Very High";
  pressureDots: number; // 1-5
  qoqTrend: number; // percent
  trendDir: "up" | "flat" | "down";
}

export const SUBURBS: SuburbData[] = [
"""

SUBURBS_FOOTER = """\
];

export const SUBURB_NAMES = SUBURBS.map((s) => s.name);

export function getSuburbBySlug(slug: string): SuburbData | undefined {
  return SUBURBS.find((s) => s.slug === slug);
}

export function getSuburbByName(name: string): SuburbData {
  return SUBURBS.find(
    (s) => s.name.toLowerCase() === name.toLowerCase()
  ) ?? SUBURBS[0];
}
"""

MODEL_HEADER = """\
// AUTO-GENERATED by scripts/update_app_data.py
// Attribute weights derived from OLS regression on Domain.com.au listing data.
// See data/regression_summary.txt for full regression output.

import { SUBURBS } from './suburbs';

export const ATTRIBUTE_WEIGHTS = {
"""

MODEL_FOOTER = """\
} as const;
"""


def generate_suburbs_ts(entries: list[dict]) -> str:
    lines = [SUBURBS_HEADER]
    for e in entries:
        trend_dir = f'"{e["trendDir"]}"'
        lines.append(f"""\
  {{
    name: "{e["name"]}",
    slug: "{e["slug"]}",
    median2br: {e["median2br"]},
    p10: {e["p10"]},
    p90: {e["p90"]},
    n: {e["n"]},
    negoPercent: {e["negoPercent"]},
    negoAmtPw: {e["negoAmtPw"]},
    pressureLevel: "{e["pressureLevel"]}",
    pressureDots: {e["pressureDots"]},
    qoqTrend: {e["qoqTrend"]},
    trendDir: {trend_dir},
  }},
""")
    lines.append(SUBURBS_FOOTER)
    return "".join(lines)


def generate_model_ts(weights: dict) -> str:
    lines = [MODEL_HEADER]
    for key, val in weights.items():
        # Format: keep integers as integers
        if isinstance(val, float) and val == int(val):
            val = int(val)
        lines.append(f"  {key}: {val},\n")
    lines.append(MODEL_FOOTER)

    # Append the rest of model.ts unchanged (interfaces + calculateRent function)
    current_model = LIB_DIR / "model.ts"
    if current_model.exists():
        content = current_model.read_text()
        # Find where ATTRIBUTE_WEIGHTS ends and copy from there
        marker = "} as const;"
        idx = content.find(marker)
        if idx != -1:
            rest = content[idx + len(marker):]
            lines.append(rest)

    return "".join(lines)


# ---------------------------------------------------------------------------
# Diff summary
# ---------------------------------------------------------------------------

def print_diff_summary(old_suburbs_path: Path, new_entries: list[dict],
                       old_weights: dict, new_weights: dict):
    print("\n## Suburb Median Changes\n")
    print(f"| {'Suburb':<22} | {'Old median2br':>14} | {'New median2br':>14} | {'Delta':>8} |")
    print(f"|{'-'*24}|{'-'*16}|{'-'*16}|{'-'*10}|")

    # Load old suburbs.ts data for comparison (crude parse)
    old_data: dict[str, int] = {}
    if old_suburbs_path.exists():
        import re
        content = old_suburbs_path.read_text()
        for m in re.finditer(r'name:\s*"([^"]+)".*?median2br:\s*(\d+)', content, re.DOTALL):
            old_data[m.group(1)] = int(m.group(2))

    for e in new_entries:
        old = old_data.get(e["name"], "—")
        new = e["median2br"]
        delta = f"{new - old:+d}" if isinstance(old, int) else "new"
        old_str = f"${old}" if isinstance(old, int) else old
        print(f"| {e['name']:<22} | {old_str:>14} | ${new:>13} | {delta:>8} |")

    print("\n## Attribute Weight Changes\n")
    print(f"| {'Attribute':<28} | {'Old':>8} | {'New':>8} | {'Delta':>8} |")
    print(f"|{'-'*30}|{'-'*10}|{'-'*10}|{'-'*10}|")

    all_keys = sorted(set(list(old_weights.keys()) + list(new_weights.keys())))
    for key in all_keys:
        old = old_weights.get(key, 0)
        new = new_weights.get(key, 0)
        delta = round(new - old, 1)
        print(f"| {key:<28} | {old:>+8} | {new:>+8} | {delta:>+8.1f} |")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    baselines = load_json(BASELINES_FILE)
    weights = load_json(WEIGHTS_FILE)

    print(f"Loaded {len(baselines)} baseline groups from {BASELINES_FILE}")
    print(f"Loaded {len(weights)} attribute weights from {WEIGHTS_FILE}\n")

    entries = build_suburb_entries(baselines)
    print(f"Built {len(entries)} suburb entries\n")

    suburbs_ts = generate_suburbs_ts(entries)
    model_ts = generate_model_ts(weights)

    OUT_SUBURBS.write_text(suburbs_ts)
    OUT_MODEL.write_text(model_ts)

    print(f"Generated → {OUT_SUBURBS}")
    print(f"Generated → {OUT_MODEL}")

    print_diff_summary(
        LIB_DIR / "suburbs.ts",
        entries,
        {  # current hardcoded weights (from lib/model.ts)
            "parking_street": 5, "parking_undercover": 35, "parking_garage": 45,
            "aircon_none": -18, "aircon_one_room": 12, "aircon_whole": 22,
            "floor_1_3": 12, "floor_4plus": 22,
            "outdoor_small_balcony": 12, "outdoor_large_balcony": 22,
            "outdoor_courtyard": 28, "pets_yes": 15,
        },
        weights,
    )

    print("\nTo apply to the app:")
    print(f"  cp {OUT_SUBURBS} {LIB_DIR / 'suburbs.ts'}")
    print(f"  cp {OUT_MODEL} {LIB_DIR / 'model.ts'}")
    print("\nReview the generated files carefully before applying.")


if __name__ == "__main__":
    main()
